export const PRODUCT_IMAGES = {
    Ao_bongda_01: require('../assets/Áo_bongda_01.jpg'),
    Bong_da_01: require('../assets/Bóng_đá_01.jpg'),
    Bong_da_02: require('../assets/Bóng_đá_02.jpg'),
    Bong_da_03: require('../assets/Bóng_đá_03.jpg'),
    Bong_tennis_01: require('../assets/Bóng_tennis_01.jpeg'),
    Quan_ao_bd_02: require('../assets/Quần_áo_bd_02.png'),
    Quanao_bongda_03: require('../assets/Quanao_bongda_03.jpg'),
    Vot_caulong_01: require('../assets/Vợt_caulong_01.jpg'),
    Vot_caulong_02: require('../assets/Vợt_caulong_02.jpg'),
    Vot_caulong_03: require('../assets/Vợt_caulong_03.jpg'),
    Vot_pickball_01: require('../assets/Vợt_pickball_01.png'),
    Vot_pickball_02: require('../assets/Vợt_pickball_02.jpg'),
};

export const PRODUCTS = [
    {
        id: '1',
        name: 'Áo Đấu Real Madrid Ronaldo #7 UCL',
        price: 320000, originalPrice: 450000,
        rating: 4.9, reviews: 214,
        image: 'Ao_bongda_01', category: '2', badge: 'HOT',
        description: 'Áo đấu phong cách Real Madrid, in tên Ronaldo số 7, có patch UCL. Chất liệu thoáng khí, thấm hút mồ hôi tốt.',
    },
    {
        id: '2',
        name: 'Bộ Quần Áo Bóng Đá Jogarbola Xanh',
        price: 280000, originalPrice: 350000,
        rating: 4.6, reviews: 98,
        image: 'Quan_ao_bd_02', category: '2', badge: 'NEW',
        description: 'Bộ quần áo bóng đá Jogarbola, thiết kế hiện đại màu xanh nổi bật. Phù hợp thi đấu và tập luyện.',
    },
    {
        id: '3',
        name: 'Bộ Quần Áo Đội Tuyển Việt Nam 2022',
        price: 250000, originalPrice: null,
        rating: 4.8, reviews: 432,
        image: 'Quanao_bongda_03', category: '2', badge: 'HOT',
        description: 'Bộ trang phục chính thức Đội tuyển Việt Nam 2022. Màu đỏ đặc trưng, đầy đủ size S/M/L/XL/XXL.',
    },
    {
        id: '4',
        name: 'Bóng Đá Tiêu Chuẩn Size 5',
        price: 150000, originalPrice: 200000,
        rating: 4.5, reviews: 310,
        image: 'Bong_da_01', category: '6', badge: 'SALE',
        description: 'Bóng đá tiêu chuẩn size 5, da PU cao cấp. Phù hợp sân cỏ nhân tạo và cỏ tự nhiên.',
    },
    {
        id: '5',
        name: 'Bóng Đá Kamito Grand Pro',
        price: 220000, originalPrice: 280000,
        rating: 4.7, reviews: 187,
        image: 'Bong_da_02', category: '6', badge: null,
        description: 'Bóng Kamito Grand Pro màu cam đen, chất liệu TPU bền bỉ, giữ hình dáng tốt sau va đập mạnh.',
    },
    {
        id: '6',
        name: 'Bóng Đá Động Lực Hàng Việt Nam',
        price: 180000, originalPrice: null,
        rating: 4.6, reviews: 256,
        image: 'Bong_da_03', category: '6', badge: null,
        description: 'Bóng Động Lực đạt chứng nhận Hàng Việt Nam Chất Lượng Cao, size 5 chuẩn FIFA.',
    },
    {
        id: '7',
        name: 'Vợt Cầu Lông Carbon Pro Xanh',
        price: 850000, originalPrice: 1100000,
        rating: 4.7, reviews: 143,
        image: 'Vot_caulong_01', category: '7', badge: 'SALE',
        description: 'Vợt carbon siêu nhẹ màu xanh cyan, cân bằng đầu vợt, phù hợp lối chơi tấn công nhanh.',
    },
    {
        id: '8',
        name: 'Vợt Cầu Lông Kamito Neon Yellow',
        price: 750000, originalPrice: 950000,
        rating: 4.8, reviews: 201,
        image: 'Vot_caulong_02', category: '7', badge: 'HOT',
        description: 'Vợt Kamito màu vàng neon, khung graphite nhẹ, độ căng dây lý tưởng 22-28 lbs cho mọi trình độ.',
    },
    {
        id: '9',
        name: 'Bộ Đôi Vợt Cầu Lông Bokai 88',
        price: 420000, originalPrice: 580000,
        rating: 4.4, reviews: 89,
        image: 'Vot_caulong_03', category: '7', badge: 'SALE',
        description: 'Combo 2 vợt Bokai 88 camo trắng xanh, thích hợp cặp đôi hoặc người mới. Khung hợp kim bền chắc.',
    },
    {
        id: '10',
        name: 'Vợt Pickleball Jogarbola Solus Carbon',
        price: 1850000, originalPrice: 2200000,
        rating: 4.9, reviews: 67,
        image: 'Vot_pickball_01', category: '8', badge: 'HOT',
        description: 'Vợt Pickleball Solus 16mm Raw Carbon Fiber, Dual Foam Core. Gradient tím hồng cao cấp, kiểm soát xuất sắc.',
    },
    {
        id: '11',
        name: 'Vợt Pickleball JOOLA Perseus Ben Johns',
        price: 2450000, originalPrice: 2800000,
        rating: 4.9, reviews: 124,
        image: 'Vot_pickball_02', category: '8', badge: 'NEW',
        description: 'Vợt JOOLA Perseus 3 chữ ký Ben Johns, lõi Propulsion Core 14mm. Chuẩn giải đấu USA Pickleball.',
    },
    {
        id: '12',
        name: 'Bóng Tennis Penn Coach (Hộp 3 quả)',
        price: 95000, originalPrice: 120000,
        rating: 4.5, reviews: 389,
        image: 'Bong_tennis_01', category: '9', badge: 'SALE',
        description: 'Bóng tennis Penn Coach hộp 3 quả, áp suất cao, lông mịn, độ nảy ổn định cho tập luyện hàng ngày.',
    },
];